language: csharp
os: linux
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
sudo: required
mono:
  - latest
dotnet: 2.0.0
script:
  - dotnet restore src/PanAndZoom
  - dotnet build src/PanAndZoom/PanAndZoom.csproj -f netstandard2.0
  - dotnet restore src/Avalonia.Controls.PanAndZoom
  - dotnet build src/Avalonia.Controls.PanAndZoom/Avalonia.Controls.PanAndZoom.csproj -f netstandard2.0
