language: csharp
os:
  - linux
  - osx
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
sudo: required
mono:
  - latest
dotnet: 1.0.1
script:
  - cd src/Avalonia.Controls.PanAndZoom
  - dotnet restore
  - dotnet build
