language: csharp
os: linux
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
sudo: required
mono:
  - latest
dotnet: 2.0.0
script:
  - ./build.sh --target "Travis" --platform "Any CPU" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6ef347bda74add05c258
    on_success: change
    on_failure: always
    on_start: never
