language: csharp
os:
  - linux
  - osx
mono:
  - latest
script:
  - ./build.sh --target "Travis" --platform "Mono" --configuration "Release"
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0e395ef26e692da2c73
    on_success: change
    on_failure: always
    on_start: never
