version: 0.4.1.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
environment:
  myget_key:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: restore.cmd
build:
  project: PanAndZoom.sln
  verbosity: minimal
after_test:
- ps: nuget\build-appveyor.ps1
artifacts:
  - path: nuget\*.nupkg
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/e218b20fbce5dbb16ebc
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
