os: Visual Studio 2015
platform:
- Any CPU
configuration:
- Release
environment:
  myget_key:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
before_build:
- cmd: restore.cmd
build:
  project: PanAndZoom.sln
  verbosity: minimal
after_test:
- ps: nuget\build-appveyor.ps1
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/e218b20fbce5dbb16ebc
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: nuget\*.nupkg
