version: 2
jobs:
  build:
    working_directory: ~/PanAndZoom
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore src/PanAndZoom
      - run: dotnet build src/PanAndZoom/PanAndZoom.csproj -f netstandard2.0
      - run: dotnet restore src/Avalonia.Controls.PanAndZoom
      - run: dotnet build src/Avalonia.Controls.PanAndZoom/Avalonia.Controls.PanAndZoom.csproj -f netstandard2.0
    notify:
      webhooks:
        - url: https://webhooks.gitter.im/e/8972de595038714ca5c1
